export const iconOptions = {
  en: {
    types: [
      { value: 'T-shirt', icon: '👕', label: 'T-shirt' },
      { value: 'Shirt', icon: '👔', label: 'Shirt' },
      { value: 'Blouse', icon: '👚', label: 'Blouse' },
      { value: 'Pants', icon: '👖', label: 'Pants' },
      { value: 'Jeans', icon: '👖', label: 'Jeans' },
      { value: 'Dress', icon: '👗', label: 'Dress' },
      { value: 'Jacket', icon: '🧥', label: 'Jacket' },
      { value: 'Coat', icon: '🧥', label: 'Coat' },
      { value: 'Skirt', icon: '👗', label: 'Skirt' },
      { value: 'Suit', icon: '🤵', label: 'Suit' },
      { value: 'Shorts', icon: '🩳', label: 'Shorts' },
      { value: 'Abaya', icon: '🥻', label: 'Abaya' },
      { value: 'Hijab', icon: '🧕', label: 'Hijab' },
      { value: 'Pajamas', icon: '🩱', label: 'Pajamas' },
      { value: 'Shoes', icon: '👟', label: 'Shoes' },
      { value: 'Bag', icon: '👜', label: 'Bag' },
      { value: 'Accessory', icon: '💍', label: 'Accessory' },
      { value: 'Sweater', icon: '🧶', label: 'Sweater' },
      { value: 'Gloves', icon: '🧤', label: 'Gloves' },
      { value: 'Hat', icon: '👒', label: 'Hat' },
      { value: 'Glasses', icon: '👓', label: 'Glasses' },
      { value: 'Socks', icon: '🧦', label: 'Socks' },
      { value: 'Belt', icon: '👔', label: 'Belt' },
      { value: 'Other', icon: '❓', label: 'Other' },
    ],
    sizes: [
      { value: 'XS', icon: '🤏', label: 'XS' },
      { value: 'S', icon: '👶', label: 'S' },
      { value: 'M', icon: '👤', label: 'M' },
      { value: 'L', icon: '👨', label: 'L' },
      { value: 'XL', icon: '👨‍🦲', label: 'XL' },
      { value: 'XXL', icon: '🫃', label: 'XXL' },
      { value: 'XXXL', icon: '🫃', label: 'XXXL' },
      { value: '32', icon: '3️⃣2️⃣', label: '32' },
      { value: '34', icon: '3️⃣4️⃣', label: '34' },
      { value: '36', icon: '3️⃣6️⃣', label: '36' },
      { value: '38', icon: '3️⃣8️⃣', label: '38' },
      { value: '40', icon: '4️⃣0️⃣', label: '40' },
      { value: '42', icon: '4️⃣2️⃣', label: '42' },
      { value: '44', icon: '4️⃣4️⃣', label: '44' },
      { value: '46', icon: '4️⃣6️⃣', label: '46' },
      { value: '48', icon: '4️⃣8️⃣', label: '48' },
      { value: '50', icon: '5️⃣0️⃣', label: '50' },
    ],
    colors: [
      { value: 'Black', icon: '⚫', label: 'Black' },
      { value: 'White', icon: '⚪', label: 'White' },
      { value: 'Gray', icon: '🔘', label: 'Gray' },
      { value: 'Blue', icon: '🔵', label: 'Blue' },
      { value: 'Navy', icon: '🌀', label: 'Navy' },
      { value: 'Red', icon: '🔴', label: 'Red' },
      { value: 'Pink', icon: '🩷', label: 'Pink' },
      { value: 'Green', icon: '🟢', label: 'Green' },
      { value: 'Olive', icon: '🫒', label: 'Olive' },
      { value: 'Yellow', icon: '🟡', label: 'Yellow' },
      { value: 'Orange', icon: '🟠', label: 'Orange' },
      { value: 'Beige', icon: '🟤', label: 'Beige' },
      { value: 'Brown', icon: '🤎', label: 'Brown' },
      { value: 'Purple', icon: '🟣', label: 'Purple' },
      { value: 'Gold', icon: '🟨', label: 'Gold' },
      { value: 'Silver', icon: '⚪', label: 'Silver' },
      { value: 'Multicolor', icon: '🌈', label: 'Multi' },
    ],
    conditions: [
      { value: 'Brand New', icon: '✨', label: 'Brand New' },
      { value: 'New without Tags', icon: '🆕', label: 'New w/o Tags' },
      { value: 'Excellent Used', icon: '⭐', label: 'Excellent' },
      { value: 'Good Used', icon: '👍', label: 'Good' },
      { value: 'Used with Minor Flaws', icon: '⚠️', label: 'Minor Flaws' },
      { value: 'Vintage/For Parts', icon: '🕰️', label: 'Vintage' },
    ],
    seasons: [
      { value: 'Summer', icon: '☀️', label: 'Summer' },
      { value: 'Winter', icon: '❄️', label: 'Winter' },
      { value: 'Fall', icon: '🍂', label: 'Fall' },
      { value: 'Spring', icon: '🌸', label: 'Spring' },
      { value: 'All Seasons', icon: '🌍', label: 'All Seasons' },
    ],
    categories: [
      { value: 'Men', icon: '👨', label: 'Men' },
      { value: 'Women', icon: '👩', label: 'Women' },
      { value: 'Boys', icon: '👦', label: 'Boys' },
      { value: 'Girls', icon: '👧', label: 'Girls' },
      { value: 'Unisex', icon: '👥', label: 'Unisex' },
    ],
    brands: [
      { value: 'Nike', icon: '✔️', label: 'Nike' },
      { value: 'Adidas', icon: '🏃', label: 'Adidas' },
      { value: 'Zara', icon: '👗', label: 'Zara' },
      { value: 'H&M', icon: '🏪', label: 'H&M' },
      { value: 'Gucci', icon: '💎', label: 'Gucci' },
      { value: 'Louis Vuitton', icon: '👑', label: 'LV' },
      { value: 'Puma', icon: '🐆', label: 'Puma' },
      { value: 'Lacoste', icon: '🐊', label: 'Lacoste' },
      { value: 'Uniqlo', icon: '🎌', label: 'Uniqlo' },
      { value: 'Mango', icon: '🥭', label: 'Mango' },
      { value: 'Bershka', icon: '🛍️', label: 'Bershka' },
      { value: 'Stradivarius', icon: '🎻', label: 'Stradivarius' },
      { value: 'Dior', icon: '💄', label: 'Dior' },
      { value: 'Chanel', icon: '💋', label: 'Chanel' },
      { value: 'Versace', icon: '🏛️', label: 'Versace' },
      { value: 'Armani', icon: '🤵', label: 'Armani' },
      { value: 'Calvin Klein', icon: '👔', label: 'CK' },
      { value: 'Tommy Hilfiger', icon: '🇺🇸', label: 'Tommy' },
      { value: 'Ralph Lauren', icon: '🐎', label: 'Ralph' },
      { value: 'Other', icon: '❓', label: 'Other' },
    ],
    fabrics: [
      { value: 'Cotton', icon: '🌿', label: 'Cotton' },
      { value: 'Polyester', icon: '🧪', label: 'Polyester' },
      { value: 'Wool', icon: '🐑', label: 'Wool' },
      { value: 'Silk', icon: '🐛', label: 'Silk' },
      { value: 'Genuine Leather', icon: '🐄', label: 'Real Leather' },
      { value: 'Synthetic Leather', icon: '🧬', label: 'Syn. Leather' },
      { value: 'Denim', icon: '👖', label: 'Denim' },
      { value: 'Linen', icon: '🌾', label: 'Linen' },
      { value: 'Velvet', icon: '✨', label: 'Velvet' },
      { value: 'Chiffon', icon: '🎭', label: 'Chiffon' },
      { value: 'Lace', icon: '🕸️', label: 'Lace' },
      { value: 'Elastane', icon: '🤸', label: 'Elastane' },
      { value: 'Cashmere', icon: '🐐', label: 'Cashmere' },
      { value: 'Other', icon: '❓', label: 'Other' },
    ],
  },
  fr: {
    types: [
      { value: 'T-shirt', icon: '👕', label: 'T-shirt' },
      { value: 'Chemise', icon: '👔', label: 'Chemise' },
      { value: 'Blouse', icon: '👚', label: 'Blouse' },
      { value: 'Pantalon', icon: '👖', label: 'Pantalon' },
      { value: 'Jean', icon: '👖', label: 'Jean' },
      { value: 'Robe', icon: '👗', label: 'Robe' },
      { value: 'Veste', icon: '🧥', label: 'Veste' },
      { value: 'Manteau', icon: '🧥', label: 'Manteau' },
      { value: 'Jupe', icon: '👗', label: 'Jupe' },
      { value: 'Costume', icon: '🤵', label: 'Costume' },
      { value: 'Short', icon: '🩳', label: 'Short' },
      { value: 'Abaya', icon: '🥻', label: 'Abaya' },
      { value: 'Hijab', icon: '🧕', label: 'Hijab' },
      { value: 'Pyjama', icon: '🩱', label: 'Pyjama' },
      { value: 'Chaussures', icon: '👟', label: 'Chaussures' },
      { value: 'Sac', icon: '👜', label: 'Sac' },
      { value: 'Accessoire', icon: '💍', label: 'Accessoire' },
      { value: 'Pull', icon: '🧶', label: 'Pull' },
      { value: 'Gants', icon: '🧤', label: 'Gants' },
      { value: 'Chapeau', icon: '👒', label: 'Chapeau' },
      { value: 'Lunettes', icon: '👓', label: 'Lunettes' },
      { value: 'Chaussettes', icon: '🧦', label: 'Chaussettes' },
      { value: 'Ceinture', icon: '👔', label: 'Ceinture' },
      { value: 'Autre', icon: '❓', label: 'Autre' },
    ],
    sizes: [
      { value: 'XS', icon: '🤏', label: 'XS' },
      { value: 'S', icon: '👶', label: 'S' },
      { value: 'M', icon: '👤', label: 'M' },
      { value: 'L', icon: '👨', label: 'L' },
      { value: 'XL', icon: '👨‍🦲', label: 'XL' },
      { value: 'XXL', icon: '🫃', label: 'XXL' },
      { value: 'XXXL', icon: '🫃', label: 'XXXL' },
      { value: '32', icon: '3️⃣2️⃣', label: '32' },
      { value: '34', icon: '3️⃣4️⃣', label: '34' },
      { value: '36', icon: '3️⃣6️⃣', label: '36' },
      { value: '38', icon: '3️⃣8️⃣', label: '38' },
      { value: '40', icon: '4️⃣0️⃣', label: '40' },
      { value: '42', icon: '4️⃣2️⃣', label: '42' },
      { value: '44', icon: '4️⃣4️⃣', label: '44' },
      { value: '46', icon: '4️⃣6️⃣', label: '46' },
      { value: '48', icon: '4️⃣8️⃣', label: '48' },
      { value: '50', icon: '5️⃣0️⃣', label: '50' },
    ],
    colors: [
      { value: 'Noir', icon: '⚫', label: 'Noir' },
      { value: 'Blanc', icon: '⚪', label: 'Blanc' },
      { value: 'Gris', icon: '🔘', label: 'Gris' },
      { value: 'Bleu', icon: '🔵', label: 'Bleu' },
      { value: 'Marine', icon: '🌀', label: 'Marine' },
      { value: 'Rouge', icon: '🔴', label: 'Rouge' },
      { value: 'Rose', icon: '🩷', label: 'Rose' },
      { value: 'Vert', icon: '🟢', label: 'Vert' },
      { value: 'Olive', icon: '🫒', label: 'Olive' },
      { value: 'Jaune', icon: '🟡', label: 'Jaune' },
      { value: 'Orange', icon: '🟠', label: 'Orange' },
      { value: 'Beige', icon: '🟤', label: 'Beige' },
      { value: 'Marron', icon: '🤎', label: 'Marron' },
      { value: 'Violet', icon: '🟣', label: 'Violet' },
      { value: 'Or', icon: '🟨', label: 'Or' },
      { value: 'Argent', icon: '⚪', label: 'Argent' },
      { value: 'Multicolore', icon: '🌈', label: 'Multi' },
    ],
    conditions: [
      { value: 'Neuf', icon: '✨', label: 'Neuf' },
      { value: 'Neuf sans étiquette', icon: '🆕', label: 'Neuf s/étiq.' },
      { value: 'Excellent état', icon: '⭐', label: 'Excellent' },
      { value: 'Bon état', icon: '👍', label: 'Bon' },
      { value: 'Usagé avec défauts mineurs', icon: '⚠️', label: 'Défauts min.' },
      { value: 'Vintage/Pour pièces', icon: '🕰️', label: 'Vintage' },
    ],
    seasons: [
      { value: 'Été', icon: '☀️', label: 'Été' },
      { value: 'Hiver', icon: '❄️', label: 'Hiver' },
      { value: 'Automne', icon: '🍂', label: 'Automne' },
      { value: 'Printemps', icon: '🌸', label: 'Printemps' },
      { value: 'Toutes saisons', icon: '🌍', label: 'Toutes' },
    ],
    categories: [
      { value: 'Homme', icon: '👨', label: 'Homme' },
      { value: 'Femme', icon: '👩', label: 'Femme' },
      { value: 'Garçon', icon: '👦', label: 'Garçon' },
      { value: 'Fille', icon: '👧', label: 'Fille' },
      { value: 'Mixte', icon: '👥', label: 'Mixte' },
    ],
    brands: [
      { value: 'Nike', icon: '✔️', label: 'Nike' },
      { value: 'Adidas', icon: '🏃', label: 'Adidas' },
      { value: 'Zara', icon: '👗', label: 'Zara' },
      { value: 'H&M', icon: '🏪', label: 'H&M' },
      { value: 'Gucci', icon: '💎', label: 'Gucci' },
      { value: 'Louis Vuitton', icon: '👑', label: 'LV' },
      { value: 'Puma', icon: '🐆', label: 'Puma' },
      { value: 'Lacoste', icon: '🐊', label: 'Lacoste' },
      { value: 'Uniqlo', icon: '🎌', label: 'Uniqlo' },
      { value: 'Mango', icon: '🥭', label: 'Mango' },
      { value: 'Bershka', icon: '🛍️', label: 'Bershka' },
      { value: 'Stradivarius', icon: '🎻', label: 'Stradivarius' },
      { value: 'Dior', icon: '💄', label: 'Dior' },
      { value: 'Chanel', icon: '💋', label: 'Chanel' },
      { value: 'Versace', icon: '🏛️', label: 'Versace' },
      { value: 'Armani', icon: '🤵', label: 'Armani' },
      { value: 'Calvin Klein', icon: '👔', label: 'CK' },
      { value: 'Tommy Hilfiger', icon: '🇺🇸', label: 'Tommy' },
      { value: 'Ralph Lauren', icon: '🐎', label: 'Ralph' },
      { value: 'Autre', icon: '❓', label: 'Autre' },
    ],
    fabrics: [
      { value: 'Coton', icon: '🌿', label: 'Coton' },
      { value: 'Polyester', icon: '🧪', label: 'Polyester' },
      { value: 'Laine', icon: '🐑', label: 'Laine' },
      { value: 'Soie', icon: '🐛', label: 'Soie' },
      { value: 'Cuir véritable', icon: '🐄', label: 'Cuir réel' },
      { value: 'Cuir synthétique', icon: '🧬', label: 'Cuir syn.' },
      { value: 'Denim', icon: '👖', label: 'Denim' },
      { value: 'Lin', icon: '🌾', label: 'Lin' },
      { value: 'Velours', icon: '✨', label: 'Velours' },
      { value: 'Mousseline', icon: '🎭', label: 'Mousseline' },
      { value: 'Dentelle', icon: '🕸️', label: 'Dentelle' },
      { value: 'Élasthanne', icon: '🤸', label: 'Élasthanne' },
      { value: 'Cachemire', icon: '🐐', label: 'Cachemire' },
      { value: 'Autre', icon: '❓', label: 'Autre' },
    ],
  },
  ar: {
    types: [
      { value: 'تيشيرت', icon: '👕', label: 'تيشيرت' },
      { value: 'قميص', icon: '👔', label: 'قميص' },
      { value: 'بلوزة', icon: '👚', label: 'بلوزة' },
      { value: 'بنطلون', icon: '👖', label: 'بنطلون' },
      { value: 'جينز', icon: '👖', label: 'جينز' },
      { value: 'فستان', icon: '👗', label: 'فستان' },
      { value: 'جاكيت', icon: '🧥', label: 'جاكيت' },
      { value: 'معطف', icon: '🧥', label: 'معطف' },
      { value: 'تنورة', icon: '👗', label: 'تنورة' },
      { value: 'بدلة', icon: '🤵', label: 'بدلة' },
      { value: 'شورت', icon: '🩳', label: 'شورت' },
      { value: 'عباية', icon: '🥻', label: 'عباية' },
      { value: 'حجاب', icon: '🧕', label: 'حجاب' },
      { value: 'بيجامة', icon: '🩱', label: 'بيجامة' },
      { value: 'حذاء', icon: '👟', label: 'حذاء' },
      { value: 'حقيبة', icon: '👜', label: 'حقيبة' },
      { value: 'إكسسوار', icon: '💍', label: 'إكسسوار' },
      { value: 'سترة', icon: '🧶', label: 'سترة' },
      { value: 'قفازات', icon: '🧤', label: 'قفازات' },
      { value: 'قبعة', icon: '👒', label: 'قبعة' },
      { value: 'نظارات', icon: '👓', label: 'نظارات' },
      { value: 'جوارب', icon: '🧦', label: 'جوارب' },
      { value: 'حزام', icon: '👔', label: 'حزام' },
      { value: 'أخرى', icon: '❓', label: 'أخرى' },
    ],
    sizes: [
      { value: 'XS', icon: '🤏', label: 'XS' },
      { value: 'S', icon: '👶', label: 'S' },
      { value: 'M', icon: '👤', label: 'M' },
      { value: 'L', icon: '👨', label: 'L' },
      { value: 'XL', icon: '👨‍🦲', label: 'XL' },
      { value: 'XXL', icon: '🫃', label: 'XXL' },
      { value: 'XXXL', icon: '🫃', label: 'XXXL' },
      { value: '32', icon: '3️⃣2️⃣', label: '32' },
      { value: '34', icon: '3️⃣4️⃣', label: '34' },
      { value: '36', icon: '3️⃣6️⃣', label: '36' },
      { value: '38', icon: '3️⃣8️⃣', label: '38' },
      { value: '40', icon: '4️⃣0️⃣', label: '40' },
      { value: '42', icon: '4️⃣2️⃣', label: '42' },
      { value: '44', icon: '4️⃣4️⃣', label: '44' },
      { value: '46', icon: '4️⃣6️⃣', label: '46' },
      { value: '48', icon: '4️⃣8️⃣', label: '48' },
      { value: '50', icon: '5️⃣0️⃣', label: '50' },
    ],
    colors: [
      { value: 'أسود', icon: '⚫', label: 'أسود' },
      { value: 'أبيض', icon: '⚪', label: 'أبيض' },
      { value: 'رمادي', icon: '🔘', label: 'رمادي' },
      { value: 'أزرق', icon: '🔵', label: 'أزرق' },
      { value: 'كحلي', icon: '🌀', label: 'كحلي' },
      { value: 'أحمر', icon: '🔴', label: 'أحمر' },
      { value: 'وردي', icon: '🩷', label: 'وردي' },
      { value: 'أخضر', icon: '🟢', label: 'أخضر' },
      { value: 'زيتي', icon: '🫒', label: 'زيتي' },
      { value: 'أصفر', icon: '🟡', label: 'أصفر' },
      { value: 'برتقالي', icon: '🟠', label: 'برتقالي' },
      { value: 'بيج', icon: '🟤', label: 'بيج' },
      { value: 'بني', icon: '🤎', label: 'بني' },
      { value: 'بنفسجي', icon: '🟣', label: 'بنفسجي' },
      { value: 'ذهبي', icon: '🟨', label: 'ذهبي' },
      { value: 'فضي', icon: '⚪', label: 'فضي' },
      { value: 'متعدد الألوان', icon: '🌈', label: 'متعدد' },
    ],
    conditions: [
      { value: 'جديد', icon: '✨', label: 'جديد' },
      { value: 'جديد بدون بطاقة', icon: '🆕', label: 'جديد ب/بطاقة' },
      { value: 'مستخدم بحالة ممتازة', icon: '⭐', label: 'ممتاز' },
      { value: 'مستخدم بحالة جيدة', icon: '👍', label: 'جيد' },
      { value: 'مستخدم مع بعض العيوب', icon: '⚠️', label: 'عيوب بسيطة' },
      { value: 'قديم أو للقطع', icon: '🕰️', label: 'قديم' },
    ],
    seasons: [
      { value: 'صيفي', icon: '☀️', label: 'صيفي' },
      { value: 'شتوي', icon: '❄️', label: 'شتوي' },
      { value: 'خريفي', icon: '🍂', label: 'خريفي' },
      { value: 'ربيعي', icon: '🌸', label: 'ربيعي' },
      { value: 'لجميع المواسم', icon: '🌍', label: 'جميع المواسم' },
    ],
    categories: [
      { value: 'رجالي', icon: '👨', label: 'رجالي' },
      { value: 'نسائي', icon: '👩', label: 'نسائي' },
      { value: 'أطفال - أولاد', icon: '👦', label: 'أولاد' },
      { value: 'أطفال - بنات', icon: '👧', label: 'بنات' },
      { value: 'للجميع', icon: '👥', label: 'للجميع' },
    ],
    brands: [
      { value: 'نايك', icon: '✔️', label: 'نايك' },
      { value: 'أديداس', icon: '🏃', label: 'أديداس' },
      { value: 'زارا', icon: '👗', label: 'زارا' },
      { value: 'اتش اند ام', icon: '🏪', label: 'H&M' },
      { value: 'غوتشي', icon: '💎', label: 'غوتشي' },
      { value: 'لويس فيتون', icon: '👑', label: 'LV' },
      { value: 'بوما', icon: '🐆', label: 'بوما' },
      { value: 'لاكوست', icon: '🐊', label: 'لاكوست' },
      { value: 'يونيكلو', icon: '🎌', label: 'يونيكلو' },
      { value: 'مانجو', icon: '🥭', label: 'مانجو' },
      { value: 'بيرشكا', icon: '🛍️', label: 'بيرشكا' },
      { value: 'ستراديفاريوس', icon: '🎻', label: 'ستراديفاريوس' },
      { value: 'ديور', icon: '💄', label: 'ديور' },
      { value: 'شانيل', icon: '💋', label: 'شانيل' },
      { value: 'فيرساتشي', icon: '🏛️', label: 'فيرساتشي' },
      { value: 'أرماني', icon: '🤵', label: 'أرماني' },
      { value: 'كالفن كلاين', icon: '👔', label: 'CK' },
      { value: 'تومي هيلفيغر', icon: '🇺🇸', label: 'تومي' },
      { value: 'رالف لورين', icon: '🐎', label: 'رالف' },
      { value: 'أخرى', icon: '❓', label: 'أخرى' },
    ],
    fabrics: [
      { value: 'قطن', icon: '🌿', label: 'قطن' },
      { value: 'بوليستر', icon: '🧪', label: 'بوليستر' },
      { value: 'صوف', icon: '🐑', label: 'صوف' },
      { value: 'حرير', icon: '🐛', label: 'حرير' },
      { value: 'جلد طبيعي', icon: '🐄', label: 'جلد طبيعي' },
      { value: 'جلد صناعي', icon: '🧬', label: 'جلد صناعي' },
      { value: 'جينز', icon: '👖', label: 'جينز' },
      { value: 'كتان', icon: '🌾', label: 'كتان' },
      { value: 'مخمل', icon: '✨', label: 'مخمل' },
      { value: 'شيفون', icon: '🎭', label: 'شيفون' },
      { value: 'دانتيل', icon: '🕸️', label: 'دانتيل' },
      { value: 'مطاطي', icon: '🤸', label: 'مطاطي' },
      { value: 'كشمير', icon: '🐐', label: 'كشمير' },
      { value: 'أخرى', icon: '❓', label: 'أخرى' },
    ],
  },
};